/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.RoboyMiddleware
{
    public class EFPose : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "roboy_middleware_msgs/msg/EFPose";

        public string ef_name;
        public Pose ef_pose;

        public EFPose()
        {
            this.ef_name = "";
            this.ef_pose = new Pose();
        }

        public EFPose(string ef_name, Pose ef_pose)
        {
            this.ef_name = ef_name;
            this.ef_pose = ef_pose;
        }
    }
}
