/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.RoboySimulation
{
    public class Collision : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "roboy_simulation_msgs/msg/Collision";

        public Header header;
        public ContactPoint[] collision;

        public Collision()
        {
            this.header = new Header();
            this.collision = new ContactPoint[0];
        }

        public Collision(Header header, ContactPoint[] collision)
        {
            this.header = header;
            this.collision = collision;
        }
    }
}
