/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RoboySimulation
{
    public class Collision : Message
    {
        public const string RosMessageName = "roboy_simulation_msgs/msg/Collision";

        public ContactPoint[] contact_points { get; set; }

        public Collision()
        {
            this.contact_points = new ContactPoint[0];
        }

        public Collision(ContactPoint[] contact_points)
        {
            this.contact_points = contact_points;
        }
    }
}
