/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.RoboySimulation
{
    public class LinkInformation : Message
    {
        public const string RosMessageName = "roboy_simulation_msgs/msg//LinkInformation";

        //  id of the link in the simulation
        public int id { get; set; }
        //  name of the link in the simulation
        public string name { get; set; }
        //  dimentions of the link
        public Vector3 dimensions { get; set; }
        //  initial pose of the link
        public Pose init_pose { get; set; }

        public LinkInformation()
        {
            this.id = 0;
            this.name = "";
            this.dimensions = new Vector3();
            this.init_pose = new Pose();
        }

        public LinkInformation(int id, string name, Vector3 dimensions, Pose init_pose)
        {
            this.id = id;
            this.name = name;
            this.dimensions = dimensions;
            this.init_pose = init_pose;
        }
    }
}
